### ISSUE TITLE
Start another task in one task

### ISSUE THREAD

**Issue by bingryan** [rusty-celery/rusty-celery#248] opened 2021-06-20 13:53 UTC
Start another task in one task。 celery uses a delay() method to start. celery  such as:

```
@app.task(base=BaseTask, bind=True)
def a(self)
	pass

@app.task(base=BaseTask, bind=True)
def b(self)
	# start a task
	a.delay()
	pass
```
How to deal with rusty-celery。

**Comment by epwalsh** [comment] 2021-06-28 16:20
I think this is a duplicate of https://github.com/rusty-celery/rusty-celery/issues/231

**Closed** 2021-07-02 06:46 UTC
